name: Deploy
on:
  push:
    branches: [ "main", "3-add-deploy-github-action"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master  
      - name: 'Create env file'
        run: |
          touch .env
          echo DISCORD_API_TOKEN=${{ secrets.DISCORD_API_KEY }} >> .env
          cat .env
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: tomclancy:${{ github.ref_name }}
          outputs: type=docker,dest=${{ runner.temp }}/tomclancy.tar
      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ${{ runner.temp }}/tomclancy.tar
          target: .
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
                docker stop $(docker ps -a -q) 
                docker run tomclancy.tar
                docker container prune