name: Deploy
on:
  push:
    branches: [ "main", "3-add-deploy-github-action"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master  
      - name: 'Create env file'
        run: |
          touch .env
          echo DISCORD_API_TOKEN=${{ secrets.DISCORD_API_KEY }} >> .env
          cat .env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: tomclancy:${{ github.ref_name }}
          outputs: type=docker,dest=tomclancy.tar
      - run: tree
      - uses: mdallasanta/ssh-scp-deploy@main
        with:
          local: './tomclancy.tar'
          remote: '~/tomclancy.tar'
          host: ${{vars.SSH_HOST}} 
          port: 22
          user: ${{secrets.SSH_USER}}   
          key: ${{secrets.SSH_PRIVATE_KEY}}  
          pre_upload: ls
          post_upload: |
                docker stop $(docker ps -a -q) 
                docker run tomclancy.tar
                docker container prune