name: Deploy
on:
  push:
    branches: [ "main", "3-add-deploy-github-action"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          build-args: discord_token=${{ secrets.DISCORD_API_KEY }}
          tags: tomclancy:${{ github.ref_name }}
          outputs: type=docker,dest=tomclancy.tar
      - run: tree
      - uses: mdallasanta/ssh-scp-deploy@main
        with:
          local: './tomclancy.tar'
          remote: '~/tomclancy.tar'
          host: ${{vars.SSH_HOST}} 
          port: 22
          user: ${{secrets.SSH_USER}}   
          key: ${{secrets.SSH_PRIVATE_KEY}}  
          pre_upload: ls
          post_upload: |
                sudo docker rm -v -f $(docker ps -qa)
                sudo docker load -i tomclancy.tar
                sudo docker run -d tomclancy:${{ github.ref_name }}
                sudo docker container prune -f